create table public.foodbanks (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name character varying null,
  description text null,
  phone_number character varying null,
  email character varying null,
  uploaded_data jsonb null,
  address text null,
  constraint foodbanks_pkey primary key (id)
) TABLESPACE pg_default;