import os
import re

from flask import Flask, request, jsonify
from supabase import create_client, Client
from dotenv import load_dotenv
import numpy as np
from google import genai

load_dotenv()

app = Flask(__name__)

supabase: Client = create_client(
    os.environ.get("SUPABASE_URL"),
    os.environ.get("SUPABASE_KEY")
)

gemini_client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

# --- helpers ---

STRUCTURED_FIELDS = {"name", "description", "phone_number", "email"}

def bad_request(message: str, details: dict | None = None, status_code: int = 400):
    payload = {"error": message}
    if details:
        payload["details"] = details
    return jsonify(payload), status_code

def get_json_body_required():
    data = request.get_json(silent=True)
    if data is None:
        return None, bad_request("Expected JSON body with Content-Type: application/json")
    if not isinstance(data, dict):
        return None, bad_request("JSON body must be an object (key/value map)")
    return data, None

def normalize_text(s: str) -> str:
    return re.sub(r"\s+", " ", (s or "").strip()).lower()

def get_text_blob_from_request() -> tuple[str | None, tuple | None]:
    """
    Accepts either:
      - Content-Type: application/json with {"text": "..."}
      - raw text/plain (or anything else) as the request body
    """
    body_json = request.get_json(silent=True)
    if isinstance(body_json, dict) and "text" in body_json:
        text = body_json.get("text")
        if not isinstance(text, str) or not text.strip():
            return None, bad_request("Field 'text' must be a non-empty string")
        return text, None

    raw = request.get_data(as_text=True)
    if not raw or not raw.strip():
        return None, bad_request("Send a non-empty text body or JSON {'text': '...'}")
    return raw, None

# --- routes ---

@app.route("/health")
def index():
    try:
        supabase.table("foodbanks").select("*").limit(1).execute()
        supabase_connected = True
    except Exception:
        supabase_connected = False
    gemini_connected = gemini_client is not None
    return jsonify({
        "UP": supabase_connected and gemini_connected,
        "services": {
            "supabase_connected": supabase_connected,
            "gemini_connected": gemini_connected}
        }), 200 if supabase_connected and gemini_connected else 503


@app.route("/foodbanks/<int:foodbank_id>")
def foodbank(foodbank_id: int):
    response = (
        supabase
        .from_("foodbanks")
        .select("*")
        .eq("id", foodbank_id)
        .execute()
    )
    if not response.data:
        return bad_request("Foodbank not found", {"id": foodbank_id}, status_code=404)
    return jsonify(response.data[0])


@app.route("/foodbanks", methods=["POST"])
def create_foodbank_structured():
    """
    Structured creation endpoint:
    - Accepts: name, description, phone_number, email
    - Rejects: uploaded_data (must not be provided here)
    - Inserts a new row; id is generated by DB identity
    """
    body, err = get_json_body_required()
    if err:
        return err

    if "uploaded_data" in body:
        return bad_request(
            "Do not send 'uploaded_data' to this endpoint. Use /foodbanks/<id>/uploaded-data instead."
        )

    allowed = {k: body.get(k) for k in STRUCTURED_FIELDS if k in body}
    if not allowed:
        return bad_request(
            "No structured fields provided",
            {"allowed_fields": sorted(STRUCTURED_FIELDS)}
        )

    response = (
        supabase
        .from_("foodbanks")
        .insert(allowed)
        .execute()
    )
    return jsonify(response.data), 201


@app.route("/foodbanks/enrich", methods=["POST"])
def enrich_foodbanks_from_blob():
    """
    Receives a text blob and returns:
      - general_description (top-level)
      - foodbanks: list of foodbanks with an extra_description for each row
    """
    text_blob, err = get_text_blob_from_request()
    if err:
        return err

    response = (
        supabase
        .from_("foodbanks")
        .select("id", "name, description, phone_number, email", "uploaded_data")
        .execute()
    )

    rows = response.data or []
    enriched = []
    for row in rows:
        row_out = dict(row)
        del(row_out["uploaded_data"])
        row_out["match_score"] = np.random.randint(0, 100)
        row_out["match_reason"] = "There is a strong need here" if row_out["match_score"] > 50 else "Not relevant"
        enriched.append(row_out)

    return jsonify({
        "recommendation_reason": "<Overall summary of recommendations by AI>",
        "recommendations": enriched
    }), 200


if __name__ == "__main__":
    app.run(debug=True)
